#!/usr/bin/env python
###################################
# mov2numpy
#
# convert .mov files to numpy file
###################################
from __future__ import division
import os
import numpy as np

from isanaht.io import loadmov

import argparse


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Convert a .mov file to a .npy file for easier handling in python',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('infile', type=str, help='input file name')
    parser.add_argument('outfile', type=str, help='output file name')
    # parser.add_argument('--head', type=str, help='xml header file describing video properties')

    args = parser.parse_args()
    infile = args.infile
    outfile = args.outfile
    # header = args.head


    assert os.path.exists(infile), "please choose a real input file"

    fr = loadmov(infile)

    np.save(outfile, fr)

    print "Saved converted output:\t%s\t(%d frames)\n" % (outfile, fr.shape[0])